// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateFolderData, CreateFolderErrors, CreateFolderResponses, DeleteFileData, DeleteFileErrors, DeleteFileResponses, DeleteFolderWithTrashData, DeleteFolderWithTrashErrors, DeleteFolderWithTrashResponses, DownloadFileData, DownloadFileErrors, DownloadFileResponses, GetFolderData, GetFolderErrors, GetFolderResponses, ListFilesData, ListFilesResponses, ListFolderContentsData, ListFolderContentsPaginatedData, ListFolderContentsPaginatedResponses, ListFolderContentsResponses, ListRootFoldersData, ListRootFoldersPaginatedData, ListRootFoldersPaginatedResponses, ListRootFoldersResponses, MoveFileData, MoveFileErrors, MoveFileResponses, MoveFolderData, MoveFolderErrors, MoveFolderResponses, RenameFolderData, RenameFolderErrors, RenameFolderResponses, UploadFileData, UploadFileErrors, UploadFileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Lists files, optionally filtered by folder ID
 */
export const listFiles = <ThrowOnError extends boolean = false>(options?: Options<ListFilesData, ThrowOnError>) => (options?.client ?? client).get<ListFilesResponses, unknown, ThrowOnError>({ url: '/files', ...options });

/**
 *
 * * API handler for file-related operations.
 * *
 * * The FileHandler is responsible for processing HTTP requests related to file operations.
 * * It handles:
 * *
 * * 1. File uploads through multipart form data
 * * 2. File downloads with optional compression
 * * 3. Listing files in folders
 * * 4. Moving files between folders
 * * 5. Deleting files (with trash integration)
 * *
 * * This component acts as an adapter in the hexagonal architecture, translating
 * * between HTTP requests/responses and application service calls. It handles
 * * HTTP-specific concerns like status codes, headers, and request parsing while
 * * delegating business logic to the application services.
 * Uploads a file
 */
export const uploadFile = <ThrowOnError extends boolean = false>(options: Options<UploadFileData, ThrowOnError>) => (options.client ?? client).post<UploadFileResponses, UploadFileErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/files/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Deletes a file (with trash support)
 */
export const deleteFile = <ThrowOnError extends boolean = false>(options: Options<DeleteFileData, ThrowOnError>) => (options.client ?? client).delete<DeleteFileResponses, DeleteFileErrors, ThrowOnError>({ url: '/files/{id}', ...options });

/**
 * Downloads a file with optional compression
 */
export const downloadFile = <ThrowOnError extends boolean = false>(options: Options<DownloadFileData, ThrowOnError>) => (options.client ?? client).get<DownloadFileResponses, DownloadFileErrors, ThrowOnError>({ url: '/files/{id}', ...options });

/**
 * Moves a file to a different folder
 */
export const moveFile = <ThrowOnError extends boolean = false>(options: Options<MoveFileData, ThrowOnError>) => (options.client ?? client).put<MoveFileResponses, MoveFileErrors, ThrowOnError>({
    url: '/files/{id}/move',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Lists root folders
 */
export const listRootFolders = <ThrowOnError extends boolean = false>(options?: Options<ListRootFoldersData, ThrowOnError>) => (options?.client ?? client).get<ListRootFoldersResponses, unknown, ThrowOnError>({ url: '/folders', ...options });

/**
 * Creates a new folder
 */
export const createFolder = <ThrowOnError extends boolean = false>(options: Options<CreateFolderData, ThrowOnError>) => (options.client ?? client).post<CreateFolderResponses, CreateFolderErrors, ThrowOnError>({
    url: '/folders',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Lists root folders with pagination
 */
export const listRootFoldersPaginated = <ThrowOnError extends boolean = false>(options?: Options<ListRootFoldersPaginatedData, ThrowOnError>) => (options?.client ?? client).get<ListRootFoldersPaginatedResponses, unknown, ThrowOnError>({ url: '/folders/paginated', ...options });

/**
 * Deletes a folder with trash functionality
 */
export const deleteFolderWithTrash = <ThrowOnError extends boolean = false>(options: Options<DeleteFolderWithTrashData, ThrowOnError>) => (options.client ?? client).delete<DeleteFolderWithTrashResponses, DeleteFolderWithTrashErrors, ThrowOnError>({ url: '/folders/{id}', ...options });

/**
 * Gets a folder by ID
 */
export const getFolder = <ThrowOnError extends boolean = false>(options: Options<GetFolderData, ThrowOnError>) => (options.client ?? client).get<GetFolderResponses, GetFolderErrors, ThrowOnError>({ url: '/folders/{id}', ...options });

/**
 * Lists folder contents
 */
export const listFolderContents = <ThrowOnError extends boolean = false>(options: Options<ListFolderContentsData, ThrowOnError>) => (options.client ?? client).get<ListFolderContentsResponses, unknown, ThrowOnError>({ url: '/folders/{id}/contents', ...options });

/**
 * Lists folder contents with pagination
 */
export const listFolderContentsPaginated = <ThrowOnError extends boolean = false>(options: Options<ListFolderContentsPaginatedData, ThrowOnError>) => (options.client ?? client).get<ListFolderContentsPaginatedResponses, unknown, ThrowOnError>({ url: '/folders/{id}/contents/paginated', ...options });

/**
 * Moves a folder to a new parent
 */
export const moveFolder = <ThrowOnError extends boolean = false>(options: Options<MoveFolderData, ThrowOnError>) => (options.client ?? client).put<MoveFolderResponses, MoveFolderErrors, ThrowOnError>({
    url: '/folders/{id}/move',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Renames a folder
 */
export const renameFolder = <ThrowOnError extends boolean = false>(options: Options<RenameFolderData, ThrowOnError>) => (options.client ?? client).put<RenameFolderResponses, RenameFolderErrors, ThrowOnError>({
    url: '/folders/{id}/rename',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
