// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateFolderData, CreateFolderErrors, CreateFolderResponses, DeleteFolderWithTrashData, DeleteFolderWithTrashErrors, DeleteFolderWithTrashResponses, GetFolderData, GetFolderErrors, GetFolderResponses, ListFolderContentsData, ListFolderContentsPaginatedData, ListFolderContentsPaginatedResponses, ListFolderContentsResponses, ListRootFoldersData, ListRootFoldersPaginatedData, ListRootFoldersPaginatedResponses, ListRootFoldersResponses, MoveFolderData, MoveFolderErrors, MoveFolderResponses, RenameFolderData, RenameFolderErrors, RenameFolderResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Lists root folders
 */
export const listRootFolders = <ThrowOnError extends boolean = false>(options?: Options<ListRootFoldersData, ThrowOnError>) => (options?.client ?? client).get<ListRootFoldersResponses, unknown, ThrowOnError>({ url: '/folders', ...options });

/**
 * Creates a new folder
 */
export const createFolder = <ThrowOnError extends boolean = false>(options: Options<CreateFolderData, ThrowOnError>) => (options.client ?? client).post<CreateFolderResponses, CreateFolderErrors, ThrowOnError>({
    url: '/folders',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Lists root folders with pagination
 */
export const listRootFoldersPaginated = <ThrowOnError extends boolean = false>(options?: Options<ListRootFoldersPaginatedData, ThrowOnError>) => (options?.client ?? client).get<ListRootFoldersPaginatedResponses, unknown, ThrowOnError>({ url: '/folders/paginated', ...options });

/**
 * Deletes a folder with trash functionality
 */
export const deleteFolderWithTrash = <ThrowOnError extends boolean = false>(options: Options<DeleteFolderWithTrashData, ThrowOnError>) => (options.client ?? client).delete<DeleteFolderWithTrashResponses, DeleteFolderWithTrashErrors, ThrowOnError>({ url: '/folders/{id}', ...options });

/**
 * Gets a folder by ID
 */
export const getFolder = <ThrowOnError extends boolean = false>(options: Options<GetFolderData, ThrowOnError>) => (options.client ?? client).get<GetFolderResponses, GetFolderErrors, ThrowOnError>({ url: '/folders/{id}', ...options });

/**
 * Lists folder contents
 */
export const listFolderContents = <ThrowOnError extends boolean = false>(options: Options<ListFolderContentsData, ThrowOnError>) => (options.client ?? client).get<ListFolderContentsResponses, unknown, ThrowOnError>({ url: '/folders/{id}/contents', ...options });

/**
 * Lists folder contents with pagination
 */
export const listFolderContentsPaginated = <ThrowOnError extends boolean = false>(options: Options<ListFolderContentsPaginatedData, ThrowOnError>) => (options.client ?? client).get<ListFolderContentsPaginatedResponses, unknown, ThrowOnError>({ url: '/folders/{id}/contents/paginated', ...options });

/**
 * Moves a folder to a new parent
 */
export const moveFolder = <ThrowOnError extends boolean = false>(options: Options<MoveFolderData, ThrowOnError>) => (options.client ?? client).put<MoveFolderResponses, MoveFolderErrors, ThrowOnError>({
    url: '/folders/{id}/move',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Renames a folder
 */
export const renameFolder = <ThrowOnError extends boolean = false>(options: Options<RenameFolderData, ThrowOnError>) => (options.client ?? client).put<RenameFolderResponses, RenameFolderErrors, ThrowOnError>({
    url: '/folders/{id}/rename',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
