// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * DTO for folder creation requests
 */
export type CreateFolderDto = {
    /**
     * Name of the folder to create
     */
    name: string;
    /**
     * Parent folder ID (None for root level)
     */
    parent_id?: string | null;
};

/**
 * DTO for folder responses
 */
export type FolderDto = {
    /**
     * Creation timestamp
     */
    created_at: number;
    /**
     * Folder ID
     */
    id: string;
    /**
     * Whether this is a root folder
     */
    is_root: boolean;
    /**
     * Last modification timestamp
     */
    modified_at: number;
    /**
     * Folder name
     */
    name: string;
    /**
     * Parent folder ID
     */
    parent_id?: string | null;
    /**
     * Path to the folder (relative)
     */
    path: string;
};

/**
 * DTO for folder move requests
 */
export type MoveFolderDto = {
    /**
     * New parent folder ID (None for root level)
     */
    parent_id?: string | null;
};

/**
 * Un DTO para representar una respuesta paginada
 */
export type PaginatedResponseDtoFolderDto = {
    /**
     * Datos en la página actual
     */
    items: Array<{
        /**
         * Creation timestamp
         */
        created_at: number;
        /**
         * Folder ID
         */
        id: string;
        /**
         * Whether this is a root folder
         */
        is_root: boolean;
        /**
         * Last modification timestamp
         */
        modified_at: number;
        /**
         * Folder name
         */
        name: string;
        /**
         * Parent folder ID
         */
        parent_id?: string | null;
        /**
         * Path to the folder (relative)
         */
        path: string;
    }>;
    /**
     * Información de paginación
     */
    pagination: PaginationDto;
};

/**
 * Un DTO para representar información de paginación
 */
export type PaginationDto = {
    /**
     * Indica si hay una página siguiente
     */
    has_next: boolean;
    /**
     * Indica si hay una página anterior
     */
    has_prev: boolean;
    /**
     * Página actual (comienza en 0)
     */
    page: number;
    /**
     * Tamaño de página
     */
    page_size: number;
    /**
     * Número total de elementos
     */
    total_items: number;
    /**
     * Número total de páginas
     */
    total_pages: number;
};

/**
 * Un DTO para representar una solicitud de paginación
 */
export type PaginationRequestDto = {
    /**
     * Página solicitada (comienza en 0)
     */
    page?: number;
    /**
     * Tamaño de página solicitado
     */
    page_size?: number;
};

/**
 * DTO for folder rename requests
 */
export type RenameFolderDto = {
    /**
     * New name for the folder
     */
    name: string;
};

export type ListRootFoldersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/folders';
};

export type ListRootFoldersResponses = {
    /**
     * List of root folders
     */
    200: Array<FolderDto>;
};

export type ListRootFoldersResponse = ListRootFoldersResponses[keyof ListRootFoldersResponses];

export type CreateFolderData = {
    body: CreateFolderDto;
    path?: never;
    query?: never;
    url: '/folders';
};

export type CreateFolderErrors = {
    /**
     * Parent folder not found
     */
    404: unknown;
    /**
     * Folder already exists
     */
    409: unknown;
};

export type CreateFolderResponses = {
    /**
     * Folder created successfully
     */
    201: FolderDto;
};

export type CreateFolderResponse = CreateFolderResponses[keyof CreateFolderResponses];

export type ListRootFoldersPaginatedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Página solicitada (comienza en 0)
         */
        page?: number;
        /**
         * Tamaño de página solicitado
         */
        page_size?: number;
    };
    url: '/folders/paginated';
};

export type ListRootFoldersPaginatedResponses = {
    /**
     * Paginated list of root folders
     */
    200: PaginatedResponseDtoFolderDto;
};

export type ListRootFoldersPaginatedResponse = ListRootFoldersPaginatedResponses[keyof ListRootFoldersPaginatedResponses];

export type DeleteFolderWithTrashData = {
    body?: never;
    path: {
        /**
         * Folder ID
         */
        id: string;
    };
    query?: never;
    url: '/folders/{id}';
};

export type DeleteFolderWithTrashErrors = {
    /**
     * Folder not found
     */
    404: unknown;
};

export type DeleteFolderWithTrashResponses = {
    /**
     * Folder deleted
     */
    204: void;
};

export type DeleteFolderWithTrashResponse = DeleteFolderWithTrashResponses[keyof DeleteFolderWithTrashResponses];

export type GetFolderData = {
    body?: never;
    path: {
        /**
         * Folder ID
         */
        id: string;
    };
    query?: never;
    url: '/folders/{id}';
};

export type GetFolderErrors = {
    /**
     * Folder not found
     */
    404: unknown;
};

export type GetFolderResponses = {
    /**
     * Folder details
     */
    200: FolderDto;
};

export type GetFolderResponse = GetFolderResponses[keyof GetFolderResponses];

export type ListFolderContentsData = {
    body?: never;
    path: {
        /**
         * Folder ID
         */
        id: string;
    };
    query?: never;
    url: '/folders/{id}/contents';
};

export type ListFolderContentsResponses = {
    /**
     * List of folder contents
     */
    200: Array<FolderDto>;
};

export type ListFolderContentsResponse = ListFolderContentsResponses[keyof ListFolderContentsResponses];

export type ListFolderContentsPaginatedData = {
    body?: never;
    path: {
        /**
         * Folder ID
         */
        id: string;
    };
    query?: {
        /**
         * Página solicitada (comienza en 0)
         */
        page?: number;
        /**
         * Tamaño de página solicitado
         */
        page_size?: number;
    };
    url: '/folders/{id}/contents/paginated';
};

export type ListFolderContentsPaginatedResponses = {
    /**
     * Paginated list of folder contents
     */
    200: PaginatedResponseDtoFolderDto;
};

export type ListFolderContentsPaginatedResponse = ListFolderContentsPaginatedResponses[keyof ListFolderContentsPaginatedResponses];

export type MoveFolderData = {
    body: MoveFolderDto;
    path: {
        /**
         * Folder ID
         */
        id: string;
    };
    query?: never;
    url: '/folders/{id}/move';
};

export type MoveFolderErrors = {
    /**
     * Folder not found
     */
    404: unknown;
    /**
     * Destination conflict
     */
    409: unknown;
};

export type MoveFolderResponses = {
    /**
     * Folder moved
     */
    200: FolderDto;
};

export type MoveFolderResponse = MoveFolderResponses[keyof MoveFolderResponses];

export type RenameFolderData = {
    body: RenameFolderDto;
    path: {
        /**
         * Folder ID
         */
        id: string;
    };
    query?: never;
    url: '/folders/{id}/rename';
};

export type RenameFolderErrors = {
    /**
     * Folder not found
     */
    404: unknown;
    /**
     * Folder name already exists
     */
    409: unknown;
};

export type RenameFolderResponses = {
    /**
     * Folder renamed
     */
    200: FolderDto;
};

export type RenameFolderResponse = RenameFolderResponses[keyof RenameFolderResponses];
