// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, type MutationOptions, queryOptions } from '@tanstack/svelte-query';

import { client } from '../client.gen';
import { createFolder, deleteFolderWithTrash, getFolder, listFolderContents, listFolderContentsPaginated, listRootFolders, listRootFoldersPaginated, moveFolder, type Options, renameFolder } from '../sdk.gen';
import type { CreateFolderData, CreateFolderResponse, DeleteFolderWithTrashData, DeleteFolderWithTrashResponse, GetFolderData, GetFolderResponse, ListFolderContentsData, ListFolderContentsPaginatedData, ListFolderContentsPaginatedResponse, ListFolderContentsResponse, ListRootFoldersData, ListRootFoldersPaginatedData, ListRootFoldersPaginatedResponse, ListRootFoldersResponse, MoveFolderData, MoveFolderResponse, RenameFolderData, RenameFolderResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listRootFoldersQueryKey = (options?: Options<ListRootFoldersData>) => createQueryKey('listRootFolders', options);

/**
 * Lists root folders
 */
export const listRootFoldersOptions = (options?: Options<ListRootFoldersData>) => queryOptions<ListRootFoldersResponse, DefaultError, ListRootFoldersResponse, ReturnType<typeof listRootFoldersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRootFolders({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRootFoldersQueryKey(options)
});

/**
 * Creates a new folder
 */
export const createFolderMutation = (options?: Partial<Options<CreateFolderData>>): MutationOptions<CreateFolderResponse, DefaultError, Options<CreateFolderData>> => {
    const mutationOptions: MutationOptions<CreateFolderResponse, DefaultError, Options<CreateFolderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createFolder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listRootFoldersPaginatedQueryKey = (options?: Options<ListRootFoldersPaginatedData>) => createQueryKey('listRootFoldersPaginated', options);

/**
 * Lists root folders with pagination
 */
export const listRootFoldersPaginatedOptions = (options?: Options<ListRootFoldersPaginatedData>) => queryOptions<ListRootFoldersPaginatedResponse, DefaultError, ListRootFoldersPaginatedResponse, ReturnType<typeof listRootFoldersPaginatedQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listRootFoldersPaginated({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRootFoldersPaginatedQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listRootFoldersPaginatedInfiniteQueryKey = (options?: Options<ListRootFoldersPaginatedData>): QueryKey<Options<ListRootFoldersPaginatedData>> => createQueryKey('listRootFoldersPaginated', options, true);

/**
 * Lists root folders with pagination
 */
export const listRootFoldersPaginatedInfiniteOptions = (options?: Options<ListRootFoldersPaginatedData>) => infiniteQueryOptions<ListRootFoldersPaginatedResponse, DefaultError, InfiniteData<ListRootFoldersPaginatedResponse>, QueryKey<Options<ListRootFoldersPaginatedData>>, number | Pick<QueryKey<Options<ListRootFoldersPaginatedData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListRootFoldersPaginatedData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listRootFoldersPaginated({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listRootFoldersPaginatedInfiniteQueryKey(options)
});

/**
 * Deletes a folder with trash functionality
 */
export const deleteFolderWithTrashMutation = (options?: Partial<Options<DeleteFolderWithTrashData>>): MutationOptions<DeleteFolderWithTrashResponse, DefaultError, Options<DeleteFolderWithTrashData>> => {
    const mutationOptions: MutationOptions<DeleteFolderWithTrashResponse, DefaultError, Options<DeleteFolderWithTrashData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteFolderWithTrash({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getFolderQueryKey = (options: Options<GetFolderData>) => createQueryKey('getFolder', options);

/**
 * Gets a folder by ID
 */
export const getFolderOptions = (options: Options<GetFolderData>) => queryOptions<GetFolderResponse, DefaultError, GetFolderResponse, ReturnType<typeof getFolderQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getFolder({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getFolderQueryKey(options)
});

export const listFolderContentsQueryKey = (options: Options<ListFolderContentsData>) => createQueryKey('listFolderContents', options);

/**
 * Lists folder contents
 */
export const listFolderContentsOptions = (options: Options<ListFolderContentsData>) => queryOptions<ListFolderContentsResponse, DefaultError, ListFolderContentsResponse, ReturnType<typeof listFolderContentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listFolderContents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listFolderContentsQueryKey(options)
});

export const listFolderContentsPaginatedQueryKey = (options: Options<ListFolderContentsPaginatedData>) => createQueryKey('listFolderContentsPaginated', options);

/**
 * Lists folder contents with pagination
 */
export const listFolderContentsPaginatedOptions = (options: Options<ListFolderContentsPaginatedData>) => queryOptions<ListFolderContentsPaginatedResponse, DefaultError, ListFolderContentsPaginatedResponse, ReturnType<typeof listFolderContentsPaginatedQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listFolderContentsPaginated({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listFolderContentsPaginatedQueryKey(options)
});

export const listFolderContentsPaginatedInfiniteQueryKey = (options: Options<ListFolderContentsPaginatedData>): QueryKey<Options<ListFolderContentsPaginatedData>> => createQueryKey('listFolderContentsPaginated', options, true);

/**
 * Lists folder contents with pagination
 */
export const listFolderContentsPaginatedInfiniteOptions = (options: Options<ListFolderContentsPaginatedData>) => infiniteQueryOptions<ListFolderContentsPaginatedResponse, DefaultError, InfiniteData<ListFolderContentsPaginatedResponse>, QueryKey<Options<ListFolderContentsPaginatedData>>, number | Pick<QueryKey<Options<ListFolderContentsPaginatedData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListFolderContentsPaginatedData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listFolderContentsPaginated({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listFolderContentsPaginatedInfiniteQueryKey(options)
});

/**
 * Moves a folder to a new parent
 */
export const moveFolderMutation = (options?: Partial<Options<MoveFolderData>>): MutationOptions<MoveFolderResponse, DefaultError, Options<MoveFolderData>> => {
    const mutationOptions: MutationOptions<MoveFolderResponse, DefaultError, Options<MoveFolderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await moveFolder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Renames a folder
 */
export const renameFolderMutation = (options?: Partial<Options<RenameFolderData>>): MutationOptions<RenameFolderResponse, DefaultError, Options<RenameFolderData>> => {
    const mutationOptions: MutationOptions<RenameFolderResponse, DefaultError, Options<RenameFolderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await renameFolder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
