/** Profile / account endpoints — ported from views/profile/profile.js. */
import { api } from '$lib/api';
import { errorDetail, throwFailed } from '$lib/api/http';
import type { User } from '$lib/api/types';
import { t } from '$lib/i18n/index.svelte';

export interface ProfilePatch {
	username?: string;
	given_name?: string;
	family_name?: string;
	preferred_locale?: string;
	notify_on_share?: boolean;
}

export async function updateProfile(patch: ProfilePatch): Promise<User> {
	const { data, error, response } = await api.PATCH('/api/auth/me/profile', { body: patch });
	if (!response.ok) {
		const detail = errorDetail(error);
		// 409 covers two distinct conflicts that share the same status. The
		// server's audit log carries the structured `reason`; the JSON body
		// only exposes a human-readable message, so we branch on that.
		if (response.status === 409) {
			const msg = detail.toLowerCase();
			const key = msg.includes('already claimed')
				? 'profile.username_immutable_error'
				: 'profile.username_taken_error';
			const fallback = msg.includes('already claimed')
				? "Your username has already been set and can't be changed."
				: 'That username is already taken.';
			throw new Error(t(key, fallback));
		}
		// 403 here means the field is governed by the identity provider.
		if (response.status === 403) {
			throw new Error(
				t(
					'profile.edit_oidc_managed',
					'Your profile is managed by your identity provider. Update it there; changes appear on your next sign-in.'
				)
			);
		}
		throw new Error(detail || `profile update failed: ${response.status}`);
	}
	if (!data) throw new Error(`profile update failed: ${response.status}`);
	return data;
}

export async function changePassword(currentPw: string, newPw: string): Promise<void> {
	const { response } = await api.PUT('/api/auth/change-password', {
		body: { current_password: currentPw, new_password: newPw }
	});
	if (!response.ok) throwFailed('password change', response);
}

export async function updateAvatar(image: string | null): Promise<void> {
	const { response } = await api.PUT('/api/auth/me/image', { body: { image } });
	if (!response.ok) throwFailed('avatar update', response);
}

export interface AppPassword {
	id: string;
	label: string;
	active?: boolean;
	created_at: string;
	last_used_at?: string;
}

/**
 * Labels the server uses for sessions auto-generated when a Nextcloud-style
 * client authenticates (vs. user-created app passwords). Ported from
 * `views/profile/profile.js`'s `AUTO_LABELS`.
 */
const AUTO_LABELS = ['Nextcloud', 'Nextcloud (OIDC)'];

/** True when an app password was auto-generated by a client session login. */
export function isAutoAppPassword(pw: Pick<AppPassword, 'label'>): boolean {
	return AUTO_LABELS.includes(pw.label);
}

export async function listAppPasswords(): Promise<AppPassword[]> {
	const { data, response } = await api.GET('/api/auth/app-passwords');
	if (!response.ok || !data) return [];
	return Array.isArray(data) ? data : (data.app_passwords ?? []);
}

/** Returns the one-time generated password (shown once). */
export async function createAppPassword(label: string): Promise<string> {
	const { data, error, response } = await api.POST('/api/auth/app-passwords', {
		body: { label }
	});
	if (!response.ok || !data) throwFailed('create app password', response, error);
	return data.password;
}

export async function revokeAppPassword(id: string): Promise<void> {
	const { response } = await api.DELETE('/api/auth/app-passwords/{id}', {
		params: { path: { id } }
	});
	if (!response.ok) throwFailed('revoke app password', response);
}
